### ISSUE TITLE
Compatibility with JAX Doesn't Appear to be Working

### ISSUE THREAD

**Issue by adam-hartshorne** [xl0/lovely-tensors#27]
With Python 3.11 and JAX 0.4.35 the following simple test fails, 

```
>>> import jax.numpy as jnp
>>> temp = jnp.array([1.0,1.0,1.0])
>>> from lovely_tensors import lovely
>>> print(lovely(temp))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/lovely_tensors/repr_str.py", line 207, in __repr__
    return to_str(self.t, plain=self.plain, verbose=self.verbose,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/anaconda3/envs/rigflow/lib/python3.11/site-packages/lovely_tensors/repr_str.py", line 129, in to_str
    dev = str(t.device) if t.device.type != "cpu" else None
                           ^^^^^^^^^^^^^
AttributeError
```

**Comment by xl0** [comment]
You probably want https://github.com/xl0/lovely-jax
I don't touch it as often, so please let me know if anything does not work.

**Comment by adam-hartshorne** [comment]
Sorry my mistake, I didn't realise they were all different libraries that required installing separately.
